VX-139: /oauth2/token generate access_token
linkernetworks/oauth pull request #13
Opened 2018-06-27 10:28 UTC by yarencheng

Depends on PR: #7 #12 #9

2018-06-27 21:43 UTC, c9s requested changes

2018-06-27 21:43 UTC, c9s commented on src/httphandler/token_test.go
> +func Test_Token(t *testing.T) {
Please don’t use underscore in the name

2018-06-28 06:23 UTC, c9s requested changes

2018-06-28 06:23 UTC, c9s commented on src/mocks/osin_storage_mock.go
> +package mocks
package name should be singular

2018-06-28 06:23 UTC, c9s commented on src/mocks/osin_storage_mock.go
> +type OsinStorageMock struct {
you are already in the osin package, you don't have to prefix it.

2018-06-28 06:23 UTC, c9s commented on src/mocks/osin_storage_mock.go
> +func (m *OsinStorageMock) Clone() osin.Storage {
we don't need Mock, if the memory storage is faster enough for testing

2018-06-28 06:57 UTC, yarencheng commented
Done. src/mocks/ is removed @c9s

2018-06-28 07:47 UTC, c9s approved these changes

2018-06-28 07:47 UTC, merged